import {describe,it,expect} from 'vitest';
import {BookkeepingEngine} from '../server/taxguard/bookkeeping/bookkeeping.engine';
import {projectBookkeeper} from '../server/bookkeeperDashboardProjection';
import {bookkeeperRequestAllowed} from '../server/bookkeeperAccess';
import {canRenderDashboardShell} from '../components/layout/dashboardAccess';
import {resolveAuthoritativeStaffWorkspace} from '../config/canonicalRouting';
import {bookkeeperKpis,transactionMatches} from '../components/workspace/bookkeeperDashboardModel';
const setup=()=>{
 const e=new BookkeepingEngine();
 e.ingestTransactions('tenant-a','client-a','bank','batch','CSV_UPLOAD',[{transactionDate:'2024-01-12',description:'Authorized record',amount:100,rawReference:'private-raw-secret',documentReferenceId:'private-doc'},{transactionDate:'2023-01-12',description:'Other year',amount:999},{transactionDate:'2024-08-12',description:'Other period',amount:50}]);
 e.ingestTransactions('tenant-b','client-a','bank','batch','MANUAL_ENTRY',[{transactionDate:'2024-01-12',description:'Other tenant',amount:500}]);
 e.ingestTransactions('tenant-a','client-b','bank','batch','MANUAL_ENTRY',[{transactionDate:'2024-01-12',description:'Other client',amount:500}]);
 return e;
};
it('isolates tenant/client/year without changing accounting authority',()=>{const e=setup();const p=projectBookkeeper(e,'tenant-a','client-a',2024);expect(p.transactions.map(t=>t.description)).toEqual(['Other period','Authorized record']);expect(e.getTransactions('tenant-a','client-a')).toHaveLength(3);});
it('isolates periods and denies foreign/unknown period IDs',()=>{const e=setup();const period=e.ensurePeriod('tenant-a','client-a',2024,'2024-Q1','2024-01-01','2024-03-31');expect(projectBookkeeper(e,'tenant-a','client-a',2024,period.id).transactions).toHaveLength(1);expect(()=>projectBookkeeper(e,'tenant-b','client-a',2024,period.id)).toThrow('PERIOD_ACCESS_DENIED');expect(()=>projectBookkeeper(e,'tenant-a','client-a',2023,period.id)).toThrow();});
it('does not fabricate periods, default accounts, reconciliations or close readiness',()=>{const e=new BookkeepingEngine();const p=projectBookkeeper(e,'tenant','client',2024);expect(p.periods).toEqual([]);expect(p.accounts).toEqual([]);expect(p.reconciliations).toEqual([]);expect(bookkeeperKpis(p)).toEqual({records:0,uncategorized:0,reconciled:0,exceptions:0,readyToClose:null});expect(p.capabilities).toEqual({mutations:false,periodClose:false,privateDocumentPreview:false});});
it('omits private references and document URLs while retaining evidence counts',()=>{const p=projectBookkeeper(setup(),'tenant-a','client-a',2024);expect(JSON.stringify(p)).not.toContain('private-raw-secret');expect(JSON.stringify(p)).not.toContain('private-doc');expect(p.transactions.find(t=>t.description==='Authorized record')?.documentCount).toBe(1);});
it('derives uncategorized and reconciled only from stored classification/state',()=>{const p=projectBookkeeper(setup(),'tenant-a','client-a',2024);expect(bookkeeperKpis(p).records).toBe(2);expect(bookkeeperKpis(p).uncategorized).toBe(2);expect(bookkeeperKpis(p).reconciled).toBe(0);expect(transactionMatches(p.transactions[0],'Reconciled')).toBe(false);expect(transactionMatches(p.transactions[0],'Unmatched')).toBe(true);});
it('maps Bookkeeper to its dedicated shell without granting preparer/reviewer/admin',()=>{const u={role:'bookkeeper',status:'active'};expect(resolveAuthoritativeStaffWorkspace(u.role)).toBe('bookkeeper_workspace');expect(canRenderDashboardShell(u,'AUTHENTICATED','bookkeeper')).toBe(true);for(const w of ['accountant','reviewer','admin','client'] as const)expect(canRenderDashboardShell(u,'AUTHENTICATED',w)).toBe(false);});
it.each(['client','accountant','reviewer','admin','super_admin','unknown'])('rejects %s from bookkeeper shell',role=>{expect(canRenderDashboardShell({role,status:'active'},'AUTHENTICATED','bookkeeper')).toBe(false);});
it.each(['INITIALIZING','UNAUTHENTICATED','ERROR'])('requires authenticated session %s',auth=>expect(canRenderDashboardShell({role:'bookkeeper',status:'active'},auth,'bookkeeper')).toBe(false));
it.each(['/api/case-authority/tenant/client/eng/2024/approvals','/api/bookkeeping/transactions/categorize','/api/bookkeeping/periods/close','/api/bookkeeping/reconciliations','/api/admin/users','/api/accountant/dashboard','/api/efile/submit','/api/security/events'])('denies Bookkeeper tax/administrative or mutation capability %s',path=>{expect(bookkeeperRequestAllowed('bookkeeper','POST',path)).toBe(false);expect(bookkeeperRequestAllowed('bookkeeper','GET',path)).toBe(false);});
it('allows only exact read endpoint and session lifecycle; query cannot expand privilege',()=>{expect(bookkeeperRequestAllowed('bookkeeper','GET','/api/bookkeeping/bookkeeper-dashboard?clientId=a')).toBe(true);expect(bookkeeperRequestAllowed('bookkeeper','POST','/api/bookkeeping/bookkeeper-dashboard')).toBe(false);expect(bookkeeperRequestAllowed('bookkeeper','GET','/api/bookkeeping/bookkeeper-dashboard/../journal-entries')).toBe(false);expect(bookkeeperRequestAllowed('bookkeeper','POST','/api/auth/logout')).toBe(true);expect(bookkeeperRequestAllowed('accountant','POST','/api/accountant/existing')).toBe(true);});

it('preserves advisory AI proposals without posting, categorizing or reconciling',()=>{const e=new BookkeepingEngine();e.ensureDefaultChartOfAccounts('tenant','client','1040_SCHED_C','fixture');e.ingestTransactions('tenant','client','bank','batch','CSV_UPLOAD',[{transactionDate:'2024-01-02',description:'office supplies',amount:-40}]);const before=e.getTransactions('tenant','client')[0];const p=projectBookkeeper(e,'tenant','client',2024);expect(p.transactions[0].ai).toBeDefined();expect(p.transactions[0].classification).toBe('AI_PROPOSED');expect(p.transactions[0].reconciliation).toBe('UNRECONCILED');expect(e.getJournalEntries('tenant','client',2024)).toEqual([]);expect(e.getTransactions('tenant','client')[0]).toEqual(before);});
it('retains actual journal creator/status and adjustments without fabricating review/audit events',()=>{const e=new BookkeepingEngine();const p=e.ensurePeriod('tenant','client',2024,'Q1','2024-01-01','2024-03-31');const a=e.ensureDefaultChartOfAccounts('tenant','client','1040_SCHED_C','fixture');const entry=e.createJournalEntry({tenantId:'tenant',clientId:'client',taxYear:2024,periodId:p.id,postingDate:'2024-02-01',transactionDate:'2024-02-01',description:'Stored adjustment',source:'ADJUSTING',isAdjusting:true,creatorUid:'maker',lines:[{id:'line-a',accountId:a[0].id,debit:10,credit:0},{id:'line-b',accountId:a[1].id,debit:0,credit:10}]});const view=projectBookkeeper(e,'tenant','client',2024,p.id);expect(view.journals[0].creator).toBe('maker');expect(view.journals[0].status).toBe(entry.status);expect(view.journals[0].adjusting).toBe(true);expect(view.journals[0].reviewer).toBeUndefined();expect(view.capabilities.periodClose).toBe(false);});
it('reads reconciliation evidence without inferring closed/reconciled period state',()=>{const e=new BookkeepingEngine();e.startReconciliation({tenantId:'tenant',clientId:'client',accountId:'bank',taxYear:2024,statementPeriodStart:'2024-01-01',statementPeriodEnd:'2024-01-31',statementBeginningBalance:0,statementEndingBalance:100});const p=projectBookkeeper(e,'tenant','client',2024);expect(p.reconciliations).toHaveLength(1);expect(p.reconciliations[0].status).toBe('IN_PROGRESS');expect(p.periods).toEqual([]);expect(bookkeeperKpis(p).readyToClose).toBeNull();});
it('scoped period reads are detached from accounting authority',()=>{const e=new BookkeepingEngine();const p=e.ensurePeriod('tenant','client',2024,'Q1','2024-01-01','2024-03-31');const read=e.getPeriods('tenant','client',2024);read[0].status='HARD_CLOSED';expect(e.getPeriods('tenant','client',2024)[0].status).toBe('OPEN');expect(p.status).toBe('OPEN');});
