import React,{useState} from 'react';
import {useApp} from '../../context/AppContext';
import {DashboardApplicationShell} from '../layout/DashboardApplicationShell';
import {useBookkeeperDashboardData,useBookkeeperClientGrants} from '../../hooks/useBookkeeperDashboardData';
import {BOOKKEEPER_MODULES,bookkeeperKpis,transactionMatches} from './bookkeeperDashboardModel';
import {ACCOUNTANT_STAGES} from './accountantDashboardModel';
import './bookkeeperDashboard.css';
export function BookkeeperDashboard() {
  const {currentUser,authLifecycleState}=useApp();
  const [module,setModule]=useState<string>('Dashboard');const [client,setClient]=useState('');const [year,setYear]=useState('');const [period,setPeriod]=useState('');const [refresh,setRefresh]=useState(0);const [collapsed,setCollapsed]=useState(false);const [filter,setFilter]=useState('All');const [query,setQuery]=useState('');const [selected,setSelected]=useState('');
  const state=useBookkeeperDashboardData(currentUser,authLifecycleState,client,year,period,refresh);
  const grants=useBookkeeperClientGrants(currentUser,authLifecycleState);
  if(!state.allowed)return <p role="alert">Authenticated Bookkeeper access with tenant context is required.</p>;
  const data=state.data;const kpis=data?bookkeeperKpis(data):null;const txn=data?.transactions.find(t=>t.id===selected);const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
  const nav=<><p>FINANCIAL OPERATIONS</p>{BOOKKEEPER_MODULES.map(m=><button key={m} title={m} aria-current={module===m?'page':undefined} onClick={()=>setModule(m)}>{collapsed?m.slice(0,2):m}</button>)}</>;
  const changeScope=()=>{setPeriod('');setSelected('');};
  return <DashboardApplicationShell workspace="bookkeeper" title="Bookkeeping & Accounting" navigation={nav} navigationCollapsed={collapsed} headerTools={<button aria-label="Toggle bookkeeper navigation" onClick={()=>setCollapsed(!collapsed)}>Menu</button>}>
    <div className="tg-bookkeeper"><header className="tg-book-welcome"><div><p>FINANCIAL RECORDS / AUTHORIZED WORKSPACE</p><h1>Bookkeeper Dashboard</h1><span>Transactions, reconciliation and general ledger evidence</span></div><button onClick={()=>setRefresh(n=>n+1)} disabled={!state.eligible}>Refresh records</button></header>
    {grants.error && <p role="alert">Authorized client grants unavailable. No clients are substituted.</p>}<section className="tg-book-scope" aria-label="Accounting scope"><label>Authorized client<select value={client} onChange={e=>{setClient(e.target.value);changeScope();}}><option value="">Select a client</option>{grants.clients.map(id=><option key={id} value={id}>{id}</option>)}</select></label><label>Tax year (2022+)<input type="number" min="2022" max="9999" value={year} placeholder="Select verified tax year" onChange={e=>{setYear(e.target.value);changeScope();}}/></label><label>Accounting period<select disabled={!data} value={period} onChange={e=>{setPeriod(e.target.value);setSelected('');}}><option value="">Full selected year</option>{data?.periods.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></section>
    <div className="tg-book-kpis">{[['Transactions / Records',kpis?.records,'All'],['Unmatched / Uncategorized',kpis?.uncategorized,'Needs Classification / Match'],['Reconciled',kpis?.reconciled,'Reconciled'],['Exceptions / Discrepancies',kpis?.exceptions,'Reconciliation'],['Ready to Close',null,'Reports'],['Period Status',data?data.periods.find(p=>p.id===period)?.status || 'Select period':null,'Reports']].map(([label,value,target])=><button key={String(label)} disabled={!data} onClick={()=>{if(target==='Reconciliation'||target==='Reports')setModule(target);else{setModule('Transactions');setFilter(String(target));}}}><span>{label}</span><strong>{value??'Unavailable'}</strong><small>{label==='Ready to Close'?'Close readiness is not certified':'Selected client / tax year'}</small></button>)}</div>
    {!state.eligible?<p className="tg-book-empty" role="status">Select an explicitly authorized client and tax year. No example transactions or taxpayer records are substituted.</p>:state.status==='loading'?<p role="status" className="tg-book-empty">Loading authorized accounting records...</p>:state.status==='error'?<p role="alert" className="tg-book-empty">Accounting records unavailable. Production requires a durable accounting provider; no local or demo data is substituted. Refresh to retry.</p>:null}
    {data && <div className="tg-book-layout"><section className="tg-book-card"><h2>{module==='Dashboard'?'Transaction Workspace':module}</h2>
    {(module==='Dashboard'||module==='Transactions') && <><div className="tg-book-filters">{['All','Uncategorized','Unmatched','Reconciled','Exceptions'].map(f=><button aria-pressed={f===filter} key={f} onClick={()=>setFilter(f)}>{f}</button>)}<label>Search authorized records<input value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="tg-book-scroll"><table><thead><tr>{['Date','Description','Amount','Account / Category','Source','Reconciliation','Evidence','Exception'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{data.transactions.filter(t=>transactionMatches(t,filter)&&t.description.toLowerCase().includes(query.toLowerCase())).map(t=><tr key={t.id} aria-selected={t.id===selected}><td>{t.date}</td><td><button onClick={()=>setSelected(t.id)}>{t.description}</button><small>{t.classification}</small></td><td>{money(t.amount)}</td><td>{t.category||'Uncategorized'}</td><td>{t.source}</td><td>{t.reconciliation}</td><td>{t.documentCount} linked</td><td>{t.duplicate==='NOT_DUPLICATE'?'No duplicate flag':t.duplicate}</td></tr>)}</tbody></table></div>{!data.transactions.length && <p className="tg-book-empty">No recorded transactions for this client, tax year and period.</p>}</>}
    {(module==='Dashboard'||module==='Reconciliation') && <><h3>Reconciliation & Exceptions</h3>{!data.reconciliations.length && <p className="tg-book-empty">No verified reconciliation records.</p>}{data.reconciliations.map(r=><article className="tg-book-evidence" key={r.id}><strong>{r.start} to {r.end}</strong><p>{r.status} / {r.matched} cleared / Variance {money(r.variance)}</p>{r.exceptions.map(e=><p key={e.id}>{e.type} / {e.status} / {money(e.amount)} / {e.notes||'No explanation recorded'} / {e.resolution||'No resolution evidence recorded'}</p>)}</article>)}</>}
    {module==='Chart of Accounts' && <><p>Existing client-wide account configuration; no default accounts are created by this view.</p>{!data.accounts.length && <p className="tg-book-empty">No recorded accounts.</p>}<div className="tg-book-scroll"><table><thead><tr><th>Account</th><th>Name</th><th>Type</th><th>Status</th></tr></thead><tbody>{data.accounts.map(a=><tr key={a.id}><td>{a.number}</td><td>{a.name}</td><td>{a.type}</td><td>{a.active?'Active':'Inactive'}</td></tr>)}</tbody></table></div></>}
    {(module==='Reports'||module==='Audit Trail') && <><h3>{module==='Reports'?'General Ledger & Adjustments':'Recorded accounting provenance'}</h3><p>Journal status is authoritative. Draft records are not treated as posted balances.</p>{!data.journals.length && <p className="tg-book-empty">No recorded journal entries or accounting evidence.</p>}<div className="tg-book-scroll"><table><thead><tr>{['Entry / Date','Description','Debit','Credit','Status','Source / Adjustment','Creator / Reviewer','Evidence'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{data.journals.map(j=><tr key={j.id}><td>{j.number}<small>{j.date}</small></td><td>{j.description}</td><td>{money(j.debit)}</td><td>{money(j.credit)}</td><td>{j.status}</td><td>{j.source} / {j.adjusting?'Adjustment':'Standard'}</td><td>{j.creator} / {j.reviewer||'Not recorded'}</td><td>{j.documentCount} linked</td></tr>)}</tbody></table></div><p>Period close readiness and immutable audit-event integration are unavailable. No close action is released.</p></>}
    </section><aside><section className="tg-book-card"><h2>Document Traceability</h2>{txn?<><h3>{txn.description}</h3><p>Source: {txn.source}</p><p>Supporting documents: {txn.documentCount} linked references</p><p>Classification: {txn.classification} / {txn.category||'Not assigned'}</p><p>Reconciliation: {txn.reconciliation}</p><p>Ledger link: {txn.journalEntryId||'Not recorded in selected scope'}</p><p>Extraction lineage and private document preview are not connected to this API. No public document links are generated.</p>{txn.ai && <><h3>AI Advisory Proposal</h3><p>{txn.ai.account} / Confidence: {txn.ai.confidence} (provider value)</p><p>{txn.ai.reasoning}</p><p>Human review required. A proposal does not authorize posting.</p></>}</>:<p>Select a recorded transaction to inspect its existing evidence links.</p>}</section><section className="tg-book-card"><h3>Human Controls</h3><p>Categorization posting, reconciliation changes, adjustments and period close are unavailable for this role until durable storage and scoped audited backend operations are released.</p><p>Tax review, approval, signature and filing permissions are not granted.</p></section></aside></div>}
    <section className="tg-book-card"><h2>Accounting Workflow</h2><div className="tg-book-workflow">{ACCOUNTANT_STAGES.slice(3,9).map((s,i)=><span key={s}><strong>{String(i+4).padStart(2,'0')}</strong>{s}</span>)}</div><p>The current engine uses Record 04, Reconcile 05, Review 06, Report 07, Plan 08 and Prepare Taxes 09. Masterplan categorization, analysis, adjustment and summary operations are accounting capabilities; they do not renumber or advance workflow stages.</p></section>
    </div></DashboardApplicationShell>;
}
