import React,{useRef,useState} from 'react';
import {useApp} from '../../context/AppContext';
import {DashboardApplicationShell} from '../layout/DashboardApplicationShell';
import {useClientServiceDashboardData,useClientServiceDetail,useClientServiceSearch} from '../../hooks/useClientServiceDashboardData';
import {CLIENT_SERVICE_MODULES,clientServiceMetrics,serviceRequestMatches,clientNextRequest,openRequest} from './clientServiceModel';
import {ACCOUNTANT_STAGES} from './accountantDashboardModel';
import {updateAge} from './practiceManagerModel';
import './clientServiceDashboard.css';
export function ClientServiceDashboard(){
 const {currentUser,authLifecycleState}=useApp();const [module,setModule]=useState('Dashboard');const [year,setYear]=useState('All');const [selectedId,setSelectedId]=useState('');const [filter,setFilter]=useState('Open');const [conversationId,setConversationId]=useState('');const [requestId,setRequestId]=useState('');const [query,setQuery]=useState('');const [refresh,setRefresh]=useState(0);const [collapsed,setCollapsed]=useState(false);const searchRef=useRef<HTMLInputElement>(null);
 const state=useClientServiceDashboardData(currentUser,authLifecycleState,year,refresh);const data=state.data;const selected=data?.cases.find(c=>c.id===selectedId);
 const conversation=useClientServiceDetail(data?.tenantId,state.scopeKey,selected,'conversation',data?.threads.some(t=>t.id===conversationId&&t.caseKey===selected?.id)?conversationId:'',refresh);
 const detail=useClientServiceDetail(data?.tenantId,state.scopeKey,selected,'request',data?.requests.some(r=>r.id===requestId&&r.caseKey===selected?.id)?requestId:'',refresh);
 const search=useClientServiceSearch(state.allowed,currentUser?.tenantId,state.sessionKey,query,year,refresh);
 if(!state.allowed)return <p role="alert">Authenticated Client Service / Operations access with tenant context is required.</p>;
 const now=new Date();const metrics=data?clientServiceMetrics(data,now):null;const next=selected&&data?clientNextRequest(data,selected.id):undefined;
 const caseLabel=(id:string)=>{const c=data?.cases.find(c=>c.id===id);return c?c.clientId+' / '+c.taxYear+' / '+c.engagementId:'Scope unavailable';};
 const choose=(id:string)=>{setSelectedId(id);setConversationId('');setRequestId('');};
 const navigation=<><p>CLIENT SERVICE</p>{CLIENT_SERVICE_MODULES.map(m=><button key={m} title={m} aria-current={module===m?'page':undefined} onClick={()=>setModule(m)}>{collapsed?m.slice(0,2):m}</button>)}</>;
 const reqRows=data?.requests.filter(r=>(!selected||r.caseKey===selected.id)&&serviceRequestMatches(r,filter,data,now))||[];
 return <DashboardApplicationShell workspace="operations" title="Client Service & Operations" navigation={navigation} navigationCollapsed={collapsed} onSearch={()=>{setModule('Client Search');setTimeout(()=>searchRef.current?.focus(),0);}} headerTools={<button aria-label="Toggle client service navigation" onClick={()=>setCollapsed(!collapsed)}>Menu</button>}>
 <div className="tg-service"><header className="tg-service-welcome"><div><small>AUTHORIZED CLIENT OPERATIONS</small><h1>Client Service Dashboard</h1><p>Requests, communication and recorded follow-up</p></div><button onClick={()=>setRefresh(n=>n+1)}>Refresh service data</button></header>
 <div className="tg-service-controls"><label>Tax year<select value={year} onChange={e=>{setYear(e.target.value);choose('');}}><option>All</option>{[...new Set(data?.cases.map(c=>c.taxYear)||[])].sort((a,b)=>b-a).map(y=><option key={y}>{y}</option>)}{year!=='All'&&!data?.cases.some(c=>String(c.taxYear)===year)&&<option>{year}</option>}</select></label><label>Authorized case<select value={selected?.id||''} onChange={e=>choose(e.target.value)}><option value="">All authorized cases</option>{data?.cases.map(c=><option key={c.id} value={c.id}>{caseLabel(c.id)}</option>)}</select></label><span>Queue views use identifiers and metadata. Select a verified request or conversation for its authorized content.</span></div>
 <div className="tg-service-kpis">{[['Open Requests',metrics?.open,'Client Requests'],['Unread Messages',metrics?.unread,'Messages'],['Appointments Today',metrics?.appointments,'Appointments'],['Waiting on Client',metrics?.waiting,'Follow-Up'],['Overdue Follow-ups',metrics?.overdue,'Follow-Up'],['Escalations',metrics?.escalations,'SLA & Escalations'],['Resolved / Completed',metrics?.resolved,'Reports']].map(([label,value,target],i)=><button key={String(label)} disabled={!data} onClick={()=>setModule(String(target))}><span>{label}</span><strong>{value??'Unavailable'}</strong><small>{i===1?'Incoming shared unread flags':i===2?'Scoped appointment adapter unavailable':i===6?'Requests + recorded follow-ups':'Authorized selected-year records'}</small></button>)}</div>
 {state.status==='loading'&&<p role="status" className="tg-service-empty">Loading authorized client service records...</p>}{state.status==='error'&&<p role="alert" className="tg-service-empty">Client service data unavailable. Production requires durable workflow and communication providers. No demonstration data or unrelated clients are substituted. Refresh to retry.</p>}
 {module==='Client Search'&&<section className="tg-service-card"><h2>Secure Client / Case Search</h2><label>Client identifier, engagement or tax year<input ref={searchRef} value={query} maxLength={100} onChange={e=>setQuery(e.target.value)}/></label><p>Server search checks role, canonical membership, tenant, client grants and selected tax year before matching. Up to 50 authorized identifier matches.</p>{!search.valid?<p className="tg-service-empty">Enter at least two characters.</p>:search.status==='loading'?<p role="status">Searching authorized cases...</p>:search.status==='error'?<p role="alert">Authorized search unavailable. No local taxpayer search is substituted.</p>:<><div className="tg-service-search-results">{search.matches.map(c=><button key={c.id} disabled={!data?.cases.some(visible=>visible.id===c.id)} onClick={()=>{choose(c.id);setModule('Dashboard');}}>{c.clientId} / {c.taxYear} / {c.engagementId}<small>{String(c.stage).padStart(2,'0')} {ACCOUNTANT_STAGES[c.stage-1]} / {c.status}</small></button>)}</div>{!search.matches.length&&<p className="tg-service-empty">No authorized cases match this search.</p>}</>}</section>}
 {data&&<div className="tg-service-layout"><section className="tg-service-card"><h2>{module==='Dashboard'?'Client Request Queue':module}</h2>
 {(module==='Dashboard'||module==='Client Requests'||module==='Reports')&&<><div className="tg-service-controls">{['All','Open','Waiting','Overdue','Escalated','Resolved'].map(f=><button key={f} disabled={f==='Escalated'} title={f==='Escalated'?'Request-specific escalation evidence unavailable; see recorded case escalations in SLA & Escalations':undefined} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="tg-service-scroll"><table><thead><tr>{['Client / Case','Request Type','Status','Priority','Owner','Age','Due Date','Required Action'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{reqRows.map(r=><tr key={r.id}><td><button onClick={()=>{choose(r.caseKey);setRequestId(r.id);}}>{caseLabel(r.caseKey)}</button></td><td>{r.type}</td><td>{r.status}</td><td>{r.priority}</td><td>Not recorded</td><td>{updateAge(r.createdAt,now)===null?'Unavailable':updateAge(r.createdAt,now)+' days'}</td><td>{r.dueDate?.slice(0,10)||'Not recorded'}</td><td><button onClick={()=>{choose(r.caseKey);setRequestId(r.id);}}>View recorded instructions</button></td></tr>)}</tbody></table></div>{!reqRows.length&&<p className="tg-service-empty">No authorized requests match this scope and filter.</p>}
 {requestId&&selected&&<section className="tg-service-detail" aria-label="Selected request instructions">{detail.status==='loading'?<p role="status">Loading authorized request instructions...</p>:detail.status==='error'?<p role="alert">Request unavailable or no longer authorized.</p>:detail.data&&'requestId' in detail.data?<><h3>{detail.data.title}</h3><p>{detail.data.description||'No required-action instructions recorded.'}</p><small>{detail.data.status}</small><p>Response and resolution mutations are not released for this role.</p></>:null}</section>}</>}
 {(module==='Dashboard'||module==='Messages')&&<><h3>Authorized Client Conversations</h3><p>Only client-visible conversations appear. Unread flags are shared source flags; per-user read receipts are unavailable.</p><div className="tg-service-scroll"><table><thead><tr><th>Client / Case</th><th>Category</th><th>Status</th><th>Incoming Unread</th><th>Recent Client-Visible Message</th><th>Conversation</th></tr></thead><tbody>{data.threads.filter(t=>!selected||t.caseKey===selected.id).map(t=><tr key={t.id}><td>{caseLabel(t.caseKey)}</td><td>{t.category}</td><td>{t.status}</td><td>{t.unread}</td><td>{t.lastMessageAt||'No visible messages'}</td><td><button onClick={()=>{choose(t.caseKey);setConversationId(t.id);setModule('Messages');}}>View conversation</button></td></tr>)}</tbody></table></div>{!data.threads.some(t=>!selected||t.caseKey===selected.id)&&<p className="tg-service-empty">No authorized client conversations.</p>}
 {conversationId&&selected&&<section className="tg-service-detail" aria-label="Authorized conversation">{conversation.status==='loading'?<p role="status">Loading authorized conversation...</p>:conversation.status==='error'?<p role="alert">Conversation unavailable or no longer authorized.</p>:conversation.data&&'messages' in conversation.data?<>{conversation.data.messages.map(m=><article key={m.id}><strong>{m.role}</strong><time>{m.createdAt}</time><p>{m.content}</p><small>{m.read?'Source marked read':'Source marked unread'}</small></article>)}{!conversation.data.messages.length&&<p>No client-visible messages recorded.</p>}<p>Sending, marking read and AI-generated contact are unavailable; this view does not contact the client.</p></>:null}</section>}</>}
 {module==='Appointments'&&<><p className="tg-service-empty">Tenant/case/tax-year appointment integration unavailable. Existing calendar records lack the scope needed for this workspace; no example appointments or inferred zero count are shown.</p><p>Appointment type, date/time, staff, status and case association will use the authorized provider contract when connected. Booking/rescheduling mutations are not released.</p></>}
 {(module==='Dashboard'||module==='Follow-Up')&&<><h3>Verified Client Follow-Up</h3><p>Unresolved requests and explicit operational follow-up tasks only. Responses pending staff review do not create a new client obligation. Stage position alone does not create an obligation.</p><div className="tg-service-scroll"><table><thead><tr><th>Client / Case</th><th>Source</th><th>Type / Blocker</th><th>Status</th><th>Due Date</th><th>Owner / Action</th></tr></thead><tbody>{data.requests.filter(r=>(!selected||r.caseKey===selected.id)&&openRequest(r)).map(r=><tr key={'r-'+r.id}><td>{caseLabel(r.caseKey)}</td><td>Recorded request</td><td>{r.type}</td><td>{r.status}</td><td>{r.dueDate?.slice(0,10)||'Not recorded'}</td><td><button onClick={()=>{choose(r.caseKey);setRequestId(r.id);setModule('Client Requests');}}>View recorded instructions</button></td></tr>)}{data.followUps.filter(f=>!selected||f.caseKey===selected.id).map(f=><tr key={'t-'+f.id}><td>{caseLabel(f.caseKey)}</td><td>Operational task</td><td>{f.type}</td><td>{f.status}</td><td>{f.dueDate?.slice(0,10)||'Not recorded'}</td><td>{f.owner||'Owner not available'} / Instructions unavailable in this contract</td></tr>)}</tbody></table></div>{!data.requests.some(r=>openRequest(r)&&(!selected||r.caseKey===selected.id))&&!data.followUps.some(f=>!selected||f.caseKey===selected.id)&&<p className="tg-service-empty">No verified follow-up obligations for this scope.</p>}</>}
 {module==='SLA & Escalations'&&<><p>SLA policy/violation evidence is unavailable. The following are recorded deadline escalations, not inferred SLA violations.</p><div className="tg-service-scroll"><table><thead><tr><th>Case / Issue</th><th>Stored Severity</th><th>Age</th><th>Status</th><th>Owner / Required Action</th></tr></thead><tbody>{data.escalations.filter(e=>!selected||e.caseKey===selected.id).map(e=><tr key={e.id}><td>{caseLabel(e.caseKey)} / {e.category}</td><td>Escalation level {e.level}</td><td>{updateAge(e.createdAt,now)===null?'Unavailable':updateAge(e.createdAt,now)+' days since registration'}</td><td>{e.status}</td><td>Not recorded / No escalation mutation released</td></tr>)}</tbody></table></div>{!data.escalations.some(e=>!selected||e.caseKey===selected.id)&&<p className="tg-service-empty">No recorded escalations for this scope.</p>}</>}
 {module==='Reports'&&<p>Resolution figures count stored resolved/closed requests and completed operational tasks. Response-time, appointment and SLA compliance reporting require authoritative contracts and are unavailable.</p>}
 {module==='Client Search'&&<p>Search results are supplied by the scoped server search above. No unrestricted taxpayer dataset is loaded.</p>}
 </section><aside><section className="tg-service-card"><h2>Client / Case Context</h2>{selected?<><h3>{selected.clientId}</h3><p>Tax year: {selected.taxYear}</p><p>Engagement: {selected.engagementId}</p><p>Workflow: {String(selected.stage).padStart(2,'0')} {ACCOUNTANT_STAGES[selected.stage-1]}</p><p>Outstanding requests: {data.requests.filter(r=>r.caseKey===selected.id&&openRequest(r)).length}</p><h3>Recorded Document Status</h3>{Object.entries(selected.documents).map(([status,count])=><p key={status}>{status}: {count}</p>)}{!Object.keys(selected.documents).length&&<p>No scoped document status records.</p>}<p>Appointments: scoped integration unavailable.</p><p>Client conversations: {data.threads.filter(t=>t.caseKey===selected.id).length}</p><h3>Next Required Client Action</h3>{next?<button onClick={()=>{setRequestId(next.id);setModule('Client Requests');}}>View instructions for {next.type} request</button>:<p>No verified open/viewed client request. No next obligation is inferred from workflow stage.</p>}</>:<p>Select an authorized case to view operational context. No default taxpayer is substituted.</p>}</section><section className="tg-service-card"><h3>Service Controls</h3><p>Escalation, messaging, request resolution and appointment mutations are unavailable until durable audited operations are released.</p><p>No tax preparation, senior review, approval, signature, filing, accounting, administration or security privileges are granted.</p></section><section className="tg-service-card"><h3>AI Assistance</h3><p>No operational AI execution is connected. Future summaries or suggestions remain advisory; this dashboard does not autonomously contact clients or alter records.</p></section></aside></div>}
 <footer className="tg-service-card"><h2>Authoritative Workflow 01?18</h2><ol className="tg-service-lifecycle">{ACCOUNTANT_STAGES.map((s,i)=><li key={s} aria-current={selected?.stage===i+1?'step':undefined}><strong>{String(i+1).padStart(2,'0')}</strong>{s}</li>)}</ol><p>Client Service facilitates communication across the existing lifecycle. Observation and follow-up never advance stages or replace approval controls.</p></footer>
 </div></DashboardApplicationShell>;
}
