import React,{useState} from 'react';
import {useApp} from '../../context/AppContext';
import {DashboardApplicationShell} from '../layout/DashboardApplicationShell';
import {usePracticeManagerDashboardData} from '../../hooks/usePracticeManagerDashboardData';
import {MANAGER_MODULES,MANAGER_STAGES,managerDistribution,managerMetrics,managerWorkload,managerMatches,activeCase,updateAge} from './practiceManagerModel';
import './practiceManagerDashboard.css';
export function PracticeManagerDashboard(){
 const {currentUser,authLifecycleState}=useApp();const [module,setModule]=useState('Dashboard');const [year,setYear]=useState('All');const [filter,setFilter]=useState('Active Cases');const [query,setQuery]=useState('');const [stage,setStage]=useState('All');const [refresh,setRefresh]=useState(0);const [collapsed,setCollapsed]=useState(false);
 const state=usePracticeManagerDashboardData(currentUser,authLifecycleState,year,refresh);
 if(!state.allowed)return <p role="alert">Authenticated Practice Manager access with tenant context is required.</p>;
 const data=state.data;const now=new Date();const metrics=data?managerMetrics(data,now):null;const workload=data?managerWorkload(data,now):[];
 const distribution=data?managerDistribution(data):MANAGER_STAGES.map((name,i)=>({name,stage:i+1,count:0}));
 const navigation=<><p>PRACTICE OPERATIONS</p>{MANAGER_MODULES.map(m=><button key={m} title={m} aria-current={module===m?'page':undefined} onClick={()=>setModule(m)}>{collapsed?m.slice(0,2):m}</button>)}</>;
 return <DashboardApplicationShell workspace="practice_manager" title="Practice Operations Command Center" navigation={navigation} navigationCollapsed={collapsed} headerTools={<button aria-label="Toggle practice manager navigation" onClick={()=>setCollapsed(!collapsed)}>Menu</button>}>
 <div className="tg-manager"><header className="tg-manager-welcome"><div><small>AUTHORIZED PRACTICE OPERATIONS</small><h1>Practice Manager Dashboard</h1><p>Case pipeline, workload and recorded deadlines</p></div><button onClick={()=>setRefresh(n=>n+1)}>Refresh operations</button></header>
 <div className="tg-manager-controls"><label>Tax year<select value={year} onChange={e=>setYear(e.target.value)}><option>All</option>{[...new Set(data?.cases.map(c=>c.taxYear)||[])].sort((a,b)=>b-a).map(y=><option key={y}>{y}</option>)}{year!=='All'&&!data?.cases.some(c=>String(c.taxYear)===year)&&<option>{year}</option>}</select></label><span>All figures use authorized cases only. Dates are evaluated in UTC; weeks run Monday to Sunday.</span></div>
 <div className="tg-manager-kpis">{[['Active Cases',metrics?.active],['Due This Week',metrics?.due],['Overdue',metrics?.overdue],['Waiting on Client',metrics?.waiting],['Ready for Review',metrics?.review],['SLA Risk / Escalations',metrics?.escalations],['Team Capacity / Workload',metrics?.active]].map(([label,value],i)=><button key={String(label)} disabled={!data} onClick={()=>{if(i===5)setModule('SLA & Escalations');else if(i===6)setModule('Team Capacity');else{setModule('Workload');setFilter(String(label));}}}><span>{label}</span><strong>{value??'Unavailable'}</strong><small>{i===5?'Recorded deadline escalations; SLA unavailable':i===6?'Active case volume; capacity unavailable':'View authorized operational cases'}</small></button>)}</div>
 {state.status==='loading'&&<p role="status" className="tg-manager-empty">Loading authorized practice operations...</p>}{state.status==='error'&&<p role="alert" className="tg-manager-empty">Practice operations unavailable. Production requires durable workflow and operations providers. No local or demonstration records are substituted. Refresh to retry.</p>}
 {data&&<><div className="tg-manager-layout"><section className="tg-manager-card"><h2>{module==='Dashboard'?'Firm Case Pipeline':module}</h2>
 {(module==='Dashboard'||module==='Workflow'||module==='Reports')&&<><h3>Workflow Distribution ? Active Cases</h3><div className="tg-manager-pipeline">{distribution.map(d=><button key={d.stage} aria-label={d.name+': '+d.count+' active cases'} onClick={()=>{setStage(String(d.stage));setModule('Workload');setFilter('Active Cases');}}><span>{String(d.stage).padStart(2,'0')} {d.name}</span><strong>{d.count}</strong><div aria-hidden="true"><i style={{width:metrics?.active?(d.count/metrics.active*100)+'%':'0%'}}/></div></button>)}</div></>}
 {(module==='Dashboard'||module==='Workload'||module==='Workflow')&&<><div className="tg-manager-controls">{['All','Active Cases','Due This Week','Overdue','Waiting on Client','Ready for Review'].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}<label>Stage<select value={stage} onChange={e=>setStage(e.target.value)}><option>All</option>{MANAGER_STAGES.map((s,i)=><option key={s} value={i+1}>{String(i+1).padStart(2,'0')} {s}</option>)}</select></label><label>Search authorized case identifiers<input value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="tg-manager-scroll"><table><thead><tr>{['Client / Case','Tax Year','Stage','Status','Responsible Staff','Recorded Due Dates','Last Update Age'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{data.cases.filter(c=>managerMatches(c,filter,now)&&(stage==='All'||c.stage===Number(stage))&&[c.clientId,c.engagementId].join(' ').toLowerCase().includes(query.toLowerCase())).map(c=><tr key={c.id}><td>{c.clientId}<small>{c.engagementId}</small></td><td>{c.taxYear}</td><td>{String(c.stage).padStart(2,'0')} {MANAGER_STAGES[c.stage-1]}</td><td>{c.status}{c.waiting&&<small>Waiting on Client</small>}{c.review&&<small>Ready for Review</small>}</td><td>{c.owners.join(', ')||'Not recorded / not visible'}</td><td>{[...new Set(c.dueDates.map(d=>d.slice(0,10)))].join(', ')||'Not recorded'}</td><td>{updateAge(c.updatedAt,now)===null?'Unavailable':updateAge(c.updatedAt,now)+' days'}</td></tr>)}</tbody></table></div>{!data.cases.length&&<p className="tg-manager-empty">No authorized case records for this scope. No taxpayer profiles or example cases are substituted.</p>}</>}
 {(module==='Dashboard'||module==='Team Capacity'||module==='Workload'||module==='Reports')&&<><h3>Team Workload</h3><p>Only active staff assigned to visible cases appear. Capacity targets and available hours are unavailable.</p><div className="tg-manager-scroll"><table><thead><tr>{['Staff Identifier','Role','Assigned Cases','Due This Week','Overdue','Review Workload','Capacity'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{workload.map(w=><tr key={w.id}><td>{w.id}</td><td>{w.role}</td><td>{w.assigned}</td><td>{w.due}</td><td>{w.overdue}</td><td>{w.review}</td><td>Unavailable</td></tr>)}</tbody></table></div>{!workload.length&&<p className="tg-manager-empty">No authorized active staff workload records.</p>}</>}
 {(module==='Dashboard'||module==='Deadlines'||module==='SLA & Escalations')&&<><h3>{module==='SLA & Escalations'?'Recorded Escalations':'Verified Deadlines'}</h3><div className="tg-manager-scroll"><table><thead><tr>{['Client / Year','Category / Authority','Due Date','Status','Stored Escalation','Owner','Age / Required Action'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{data.deadlines.filter(d=>module!=='SLA & Escalations'||(!['MET','WAIVED'].includes(d.status)&&d.escalation>0)).map(d=><tr key={d.id}><td>{d.clientId} / {d.taxYear}</td><td>{d.category} / {d.authority}</td><td>{d.dueDate.slice(0,10)}</td><td>{d.status}</td><td>Level {d.escalation}</td><td>{d.owner||'Not recorded'}</td><td>{updateAge(d.createdAt,now)===null?'Age unavailable':updateAge(d.createdAt,now)+' days since registration'}<small>Required action not recorded in deadline contract</small></td></tr>)}</tbody></table></div>{!data.deadlines.length&&<p className="tg-manager-empty">No verified deadline records. Regulatory dates are not inferred.</p>}<p>SLA policy and violation evidence are unavailable. Stored deadline escalation levels are not presented as SLA violations. This read does not run an escalation sweep.</p></>}
 {module==='Reports'&&<p>Completion trends, throughput durations and SLA compliance reports are unavailable until authoritative transition history and policy contracts are connected.</p>}
 </section><aside><section className="tg-manager-card"><h2>Workload Concentration</h2>{distribution.filter(d=>d.count>0).sort((a,b)=>b.count-a.count).slice(0,4).map(d=><p key={d.stage}><strong>{d.name}</strong>: {d.count} active cases</p>)}{!metrics?.active&&<p>No active workload concentration to display.</p>}<p>Concentration identifies where work is accumulating. It does not prove a delay or SLA failure; stage dwell-time evidence is unavailable.</p><p>Reconciliation backlog: {distribution[4].count} stage 05 cases</p><p>Review backlog: {metrics?.review} verified review-ready cases</p><p>Filing-stage workload: {distribution[11].count} stage 12 cases</p></section><section className="tg-manager-card"><h3>Management Controls</h3><p>Reassignment and escalation mutations are unavailable until scoped durable operations and audit evidence are released.</p><p>No administrative, security, accounting posting, final tax approval, signature or filing privileges are granted.</p></section><section className="tg-manager-card"><h3>AI / Human Oversight</h3><p>No AI analysis provider is connected to this operational contract. Any future AI recommendation remains advisory; human approval and existing workflow gates control action.</p></section></aside></div></>}
 <footer className="tg-manager-card"><h2>Authoritative Lifecycle 01?18</h2><ol className="tg-manager-lifecycle">{MANAGER_STAGES.map((s,i)=><li key={s}><strong>{String(i+1).padStart(2,'0')}</strong>{s}</li>)}</ol><p>Existing persisted stage names and numbers remain controlling. Observation never advances a case or approves, signs or files a return.</p></footer>
 </div></DashboardApplicationShell>;
}
