import type {PracticeManagerSnapshot,PracticeManagerCase} from '../../types/practiceManagerDashboard';
import {ACCOUNTANT_STAGES} from './accountantDashboardModel';
export const MANAGER_STAGES=ACCOUNTANT_STAGES;
export const MANAGER_MODULES=['Dashboard','Workload','Deadlines','Team Capacity','SLA & Escalations','Workflow','Reports'];
export const activeCase=(c:PracticeManagerCase)=>['DRAFT','ACTIVE','BLOCKED','IN_REVIEW','READY','APPROVED','FILED','RESOLVED'].includes(c.status);
export function weekRange(now:Date){const day=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()));day.setUTCDate(day.getUTCDate()-((day.getUTCDay()+6)%7));const end=new Date(day);end.setUTCDate(end.getUTCDate()+6);return [day.toISOString().slice(0,10),end.toISOString().slice(0,10)];}
export function managerMatches(c:PracticeManagerCase,filter:string,now:Date) {const today=now.toISOString().slice(0,10);const [start,end]=weekRange(now);return filter==='Overdue'?activeCase(c)&&c.dueDates.some(d=>new Date(d).toISOString().slice(0,10)<today):filter==='Due This Week'?activeCase(c)&&c.dueDates.some(d=>new Date(d).toISOString().slice(0,10)>=start&&new Date(d).toISOString().slice(0,10)<=end):filter==='Waiting on Client'?activeCase(c)&&c.waiting:filter==='Ready for Review'?activeCase(c)&&c.review:filter==='Active Cases'?activeCase(c):true;}
export function managerMetrics(data:PracticeManagerSnapshot,now:Date){return {active:data.cases.filter(activeCase).length,due:data.cases.filter(c=>managerMatches(c,'Due This Week',now)).length,overdue:data.cases.filter(c=>managerMatches(c,'Overdue',now)).length,waiting:data.cases.filter(c=>managerMatches(c,'Waiting on Client',now)).length,review:data.cases.filter(c=>managerMatches(c,'Ready for Review',now)).length,escalations:data.deadlines.filter(d=>!['MET','WAIVED'].includes(d.status)&&d.escalation>0).length,capacity:null};}
export function managerWorkload(data:PracticeManagerSnapshot,now:Date){return data.staff.map(s=>{const cases=data.cases.filter(c=>activeCase(c)&&c.owners.includes(s.id));return {...s,assigned:cases.length,due:cases.filter(c=>managerMatches(c,'Due This Week',now)).length,overdue:cases.filter(c=>managerMatches(c,'Overdue',now)).length,review:cases.filter(c=>c.review).length};});}
export function updateAge(updatedAt:string|undefined,now:Date){if(!updatedAt||!Number.isFinite(Date.parse(updatedAt))||Date.parse(updatedAt)>now.getTime())return null;return Math.floor((now.getTime()-Date.parse(updatedAt))/86400000);}

export function managerDistribution(data:PracticeManagerSnapshot){return MANAGER_STAGES.map((name,i)=>({name,stage:i+1,count:data.cases.filter(c=>activeCase(c)&&c.stage===i+1).length}));}
