import React, { useEffect, useRef, useState } from 'react';
import { useApp } from '../../context/AppContext';
import { api } from '../../services/api';
import { useReviewerDashboardData } from '../../hooks/useReviewerDashboardData';
import { DashboardApplicationShell } from '../layout/DashboardApplicationShell';
import { REVIEW_FILTERS, REVIEW_TABS, REVIEWER_STAGES, reviewFilter, reviewerDecisionBlock } from './reviewerDashboardModel';
import { ReviewEmpty, ReviewerExceptionPanel, ReviewerQualityPanel, ReviewerReadPanel } from './ReviewerCasePanels';
import './reviewerDashboard.css';

const kpis=['Ready for Review','High Risk','Returned','Awaiting Approval','Due Today','Overdue'];
export function ReviewerDashboard() {
  const {currentUser,authLifecycleState}=useApp();
  const [selectedId,setSelectedId]=useState(''); const [refresh,setRefresh]=useState(0);
  const [filter,setFilter]=useState('Ready for Review'); const [query,setQuery]=useState(''); const [year,setYear]=useState('All');
  const [tab,setTab]=useState('Overview'); const [collapsed,setCollapsed]=useState(false);
  const data=useReviewerDashboardData(currentUser,authLifecycleState,selectedId,refresh);
  const [returnId,setReturnId]=useState(''); const [decision,setDecision]=useState<'APPROVE'|'RETURN'|null>(null);
  const [reason,setReason]=useState(''); const [corrections,setCorrections]=useState(''); const [confirmed,setConfirmed]=useState(false);
  const [busy,setBusy]=useState(false); const [notice,setNotice]=useState<{key:string;text:string;error:boolean}|null>(null);
  const searchRef=useRef<HTMLInputElement>(null); const dialogRef=useRef<HTMLDialogElement>(null); const pendingRef=useRef(false);
  const activeKey=useRef(data.caseKey); activeKey.current=data.caseKey;
  useEffect(()=>{setReturnId('');setDecision(null);setReason('');setCorrections('');setConfirmed(false);},[data.caseKey]);
  useEffect(()=>{const dialog=dialogRef.current;if(decision && !dialog?.open)dialog?.showModal();else if(!decision && dialog?.open)dialog.close();},[decision]);
  if(!data.allowed) return <div role="alert">Authenticated Reviewer / Senior access with tenant context is required.</div>;
  const now=new Date(); const today=[now.getFullYear(),String(now.getMonth()+1).padStart(2,'0'),String(now.getDate()).padStart(2,'0')].join('-');
  const rows=data.queue.data;
  const visible=rows.filter(r=>reviewFilter(r,filter,today) && (year==='All'||String(r.scope.taxYear)===year) && (r.clientName+' '+r.preparerName+' '+r.scope.taxYear).toLowerCase().includes(query.toLowerCase()));
  const snapshot=data.snapshot.data;
  const selectedReturn=snapshot?.returns.find(r=>r.returnId===returnId);
  const approveBlock=snapshot ? reviewerDecisionBlock(snapshot,selectedReturn,'APPROVE') : 'Load an authorized case.';
  const returnBlock=snapshot ? reviewerDecisionBlock(snapshot,selectedReturn,'RETURN') : 'Load an authorized case.';
  const choose=(id:string)=>{if(pendingRef.current)return;setSelectedId(id);setTab('Overview');};
  const changeTab=(next:string)=>{if(!busy)setTab(next);};
  const navigation=<div className="tg-review-nav"><button onClick={()=>setFilter('All Assigned')}>Review Center</button><h3>MY REVIEW QUEUE</h3>{REVIEW_FILTERS.map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}<h3>CASE WORKSPACE</h3>{REVIEW_TABS.map(t=><button key={t} disabled={!data.selected || busy} onClick={()=>changeTab(t)}>{t}</button>)}<h3>QUALITY & GOVERNANCE</h3><p>Independent human review<br/>Server-controlled decisions</p></div>;
  const submit=async(event:React.FormEvent)=>{
    event.preventDefault();if(pendingRef.current || !snapshot || !selectedReturn || !decision)return;
    const blocked=reviewerDecisionBlock(snapshot,selectedReturn,decision);
    if(blocked || !confirmed || reason.trim().length<20 || (decision==='RETURN' && corrections.trim().length<20))return;
    pendingRef.current=true;setBusy(true);const key=data.caseKey;
    try {
      const result=await api.reviewer.decide(snapshot.scope,{version:snapshot.case.version ?? snapshot.case.revision,operationId:'review_'+crypto.randomUUID().replaceAll('-',''),returnId:selectedReturn.returnId,decision,reason:reason.trim(),corrections:decision==='RETURN'?corrections.trim():undefined,confirmed:true});
      if(!Number.isSafeInteger(result.version))throw Error('Decision acknowledgement unavailable');
      if(activeKey.current===key){setNotice({key,text:decision==='APPROVE'?'Reviewer approval recorded by the server. Signature and filing remain separate.':'Return-to-preparer decision and correction instructions recorded by the server.',error:false});setDecision(null);setRefresh(n=>n+1);}
    } catch {
      if(activeKey.current===key)setNotice({key,text:'The decision was not confirmed. Access, credentials, stage, findings or case version may have changed. Refresh before retrying; no local success is assumed.',error:true});
    } finally {pendingRef.current=false;setBusy(false);}
  };
  return <DashboardApplicationShell id="reviewer-dashboard-shell" workspace="reviewer" title="Reviewer / Senior · Quality Control" navigation={navigation} navigationCollapsed={collapsed} onSearch={()=>searchRef.current?.focus()} headerTools={<button onClick={()=>setCollapsed(!collapsed)} aria-label="Toggle reviewer navigation">☰</button>}>
    <div className="tg-reviewer">
      <div className="tg-review-kpis">{kpis.map((label,i)=><button key={label} className={'tg-review-kpi tg-review-kpi-'+i} disabled={data.queue.status!=='ready'} aria-pressed={filter===label} onClick={()=>setFilter(label)}><span>{label}</span><strong>{data.queue.status==='ready'?rows.filter(r=>reviewFilter(r,label,today)).length:'—'}</strong><small>{label==='High Risk'?'Critical return diagnostics':label==='Overdue'?'Recorded deadlines · SLA unavailable':'View authorized cases'}</small></button>)}</div>
      <section className="tg-review-card tg-review-queue"><h2>Quality Review Queue <button disabled={busy} onClick={()=>setRefresh(n=>n+1)}>Refresh</button></h2><div className="tg-review-filters">{REVIEW_FILTERS.slice(0,6).map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}<label>Search authorized cases<input ref={searchRef} value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Tax year<select value={year} onChange={e=>setYear(e.target.value)}><option>All</option>{[...new Set(rows.map(r=>r.scope.taxYear))].sort((a,b)=>b-a).map(y=><option key={y}>{y}</option>)}</select></label></div>
        {data.queue.status==='loading' && <p role="status">Loading authorized review cases…</p>}{data.queue.status==='error' && <p role="alert">{data.queue.error}</p>}
        <div className="tg-review-scroll"><table><thead><tr>{['Client','Tax Year / Period','Current Stage','Preparer','Risk / Priority','Review Status','Due Date'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{visible.map(r=><tr key={r.id} aria-selected={r.id===selectedId}><td><button disabled={busy} onClick={()=>choose(r.id)}>{r.clientName}</button></td><td>{r.scope.taxYear}</td><td>{String(r.activeStage).padStart(2,'0')} {REVIEWER_STAGES[r.activeStage-1]}</td><td>{r.preparerName}</td><td>{r.highRisk?'Critical diagnostics':r.priority || 'Not recorded'}</td><td>{r.reviewStatus}</td><td>{r.dueDate?.slice(0,10) || 'Not recorded'}</td></tr>)}</tbody></table></div>{data.queue.status==='ready' && !visible.length && <ReviewEmpty>No authorized cases match this review queue.</ReviewEmpty>}
      </section>
      {!data.selected ? <section className="tg-review-card tg-review-light"><ReviewEmpty>Select an authorized case to inspect its review evidence. No default taxpayer is substituted.</ReviewEmpty></section> : <div className="tg-review-body"><section className="tg-review-card tg-review-light"><h2>{data.selected.clientName}<small>{data.selected.scope.taxYear} · {data.selected.preparerName} · {data.selected.reviewStatus}</small></h2><div className="tg-review-tabs" role="tablist" aria-label="Reviewer case workspace">{REVIEW_TABS.map(t=><button key={t} disabled={busy} id={'review-tab-'+t.replaceAll(' ','-').replaceAll('/','-')} role="tab" tabIndex={tab===t?0:-1} aria-selected={tab===t} aria-controls="review-case-panel" onClick={()=>changeTab(t)} onKeyDown={e=>{const index=REVIEW_TABS.indexOf(t);const next=e.key==='ArrowRight'?(index+1)%REVIEW_TABS.length:e.key==='ArrowLeft'?(index+REVIEW_TABS.length-1)%REVIEW_TABS.length:e.key==='Home'?0:e.key==='End'?REVIEW_TABS.length-1:-1;if(next>=0){e.preventDefault();changeTab(REVIEW_TABS[next]);document.getElementById('review-tab-'+REVIEW_TABS[next].replaceAll(' ','-').replaceAll('/','-'))?.focus();}}}>{t}</button>)}</div>
        <div id="review-case-panel" role="tabpanel" aria-labelledby={'review-tab-'+tab.replaceAll(' ','-').replaceAll('/','-')}>
          {data.snapshot.status==='loading' && <p role="status">Loading the authorized case and tax-year review evidence…</p>}{data.snapshot.status==='error' && <p role="alert">{data.snapshot.error}</p>}
          {snapshot && !snapshot.decisionsAvailable && <p role="status" className="tg-review-empty">Approve / return is unavailable: durable reviewer decision storage has not been established for production.</p>}
          {snapshot && (tab==='Approval' ? <><h3>Independent approval / return to preparer</h3><p>Reviewer: {currentUser!.name}. Server assignment, current professional credentials and maker-checker policy govern each decision.</p><label>Recorded return<select value={returnId} disabled={busy} onChange={e=>setReturnId(e.target.value)}><option value="">Select a return</option>{snapshot.returns.map(r=><option key={r.returnId} value={r.returnId}>{r.returnType} · {r.jurisdiction} · {r.status}</option>)}</select></label><div className="tg-review-actions"><button disabled={Boolean(approveBlock)||busy} title={approveBlock || 'Confirm independent reviewer approval'} onClick={()=>{setDecision('APPROVE');setConfirmed(false);}}>Approve</button><button disabled={Boolean(returnBlock)||busy} title={returnBlock || 'Record corrections and return to preparer'} onClick={()=>{setDecision('RETURN');setConfirmed(false);}}>Return to Preparer</button></div>{approveBlock && <p>Approval: {approveBlock}</p>}{returnBlock && <p>Return: {returnBlock}</p>}<p>Approval does not move the case to signature or filing. There is no automatic tax-record edit.</p></> : tab==='Client Information' ? <dl><dt>Client</dt><dd>{data.selected.clientName}</dd><dt>Tax Year</dt><dd>{snapshot.scope.taxYear}</dd><dt>Preparer</dt><dd>{data.selected.preparerName}</dd><dt>Current stage</dt><dd>{REVIEWER_STAGES[snapshot.case.activeStage-1]}</dd><dt>Filing status / jurisdiction / dependents</dt><dd>Year-specific client profile integration unavailable in this case contract.</dd></dl> : <ReviewerReadPanel key={data.caseKey+':'+tab} tab={tab} snapshot={snapshot}/>) }
        </div>
      </section><aside><section className="tg-review-card tg-review-light"><h3>Maker-checker</h3><p>{snapshot?.independentReviewer ? 'Assigned independent professional verified at last read. Decisions are rechecked by the server.' : 'Decision eligibility has not been verified.'}</p><p>Preparer: {data.selected.preparerName}</p><p>Review approval remains separate from taxpayer signature and filing.</p></section>{snapshot && <><section className="tg-review-card tg-review-light"><ReviewerQualityPanel snapshot={snapshot}/></section><section className="tg-review-card tg-review-light"><ReviewerExceptionPanel snapshot={snapshot}/></section></>}</aside></div>}
      {notice && (notice.key===data.caseKey || (notice.key.startsWith(data.sessionKey+':') && notice.key.endsWith(':'+data.selected?.id))) && <p role={notice.error?'alert':'status'} className="tg-review-notice">{notice.text}</p>}
      <ol className="tg-review-workflow" aria-label="Authoritative 18-stage workflow">{REVIEWER_STAGES.map((s,i)=><li key={s} aria-current={snapshot?.case.activeStage===i+1?'step':undefined}><strong>{String(i+1).padStart(2,'0')}</strong>{s}</li>)}</ol>
      <p className="tg-review-footnote">This dashboard projects the existing engine: Prepare 09 · Review 06 · Approve 10 · Sign 11 · File 12. Review evidence is not a substitute for downstream human gates.</p>
      <dialog ref={dialogRef} className="tg-review-dialog" onCancel={event=>{if(busy)event.preventDefault();else setDecision(null);}} onClose={()=>{if(!busy)setDecision(null);}} aria-labelledby="review-decision-title"><form onSubmit={submit}><h2 id="review-decision-title">{decision==='APPROVE'?'Confirm reviewer approval':'Return to preparer'}</h2><p>{data.selected?.clientName} · {data.selected?.scope.taxYear} · {selectedReturn?.jurisdiction}</p><label>Review reason (at least 20 characters)<textarea required minLength={20} maxLength={4000} value={reason} disabled={busy} onChange={e=>setReason(e.target.value)}/></label>{decision==='RETURN' && <label>Issues requiring correction (at least 20 characters)<textarea required minLength={20} maxLength={4000} value={corrections} disabled={busy} onChange={e=>setCorrections(e.target.value)}/></label>}<label className="tg-review-confirm"><input type="checkbox" required checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/>I confirm this independent human review decision for this case and tax year.</label>{notice?.key===data.caseKey && notice.error && <p role="alert">{notice.text}</p>}<div className="tg-review-actions"><button type="button" disabled={busy} onClick={()=>setDecision(null)}>Cancel</button><button disabled={busy || !confirmed || reason.trim().length<20 || (decision==='RETURN' && corrections.trim().length<20)} type="submit">{busy?'Recording decision…':'Record decision'}</button></div></form></dialog>
    </div>
  </DashboardApplicationShell>;
}
