import type { Agent } from './types';

/** Canonical metadata only. DRAFT does not authorize execution. */
export const CANONICAL_AGENTS: readonly Readonly<Omit<Agent, 'created_at' | 'updated_at'>>[] = Object.freeze([
  {
    "agent_id": "A00",
    "agent_name": "Supervisor / Orchestrator",
    "category": "SUPERVISOR",
    "description": "Supervisor registry identity; orchestration is not activated.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A01",
    "agent_name": "CLIENT SERVICES 01",
    "category": "CLIENT_SERVICES",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A02",
    "agent_name": "CLIENT SERVICES 02",
    "category": "CLIENT_SERVICES",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A03",
    "agent_name": "CLIENT SERVICES 03",
    "category": "CLIENT_SERVICES",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A04",
    "agent_name": "CLIENT SERVICES 04",
    "category": "CLIENT_SERVICES",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A05",
    "agent_name": "Document Intake",
    "category": "DOCUMENT_INTELLIGENCE",
    "description": "Directive identifies this capability. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A06",
    "agent_name": "Document Classification",
    "category": "DOCUMENT_INTELLIGENCE",
    "description": "Directive identifies this capability. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A07",
    "agent_name": "OCR / Extraction",
    "category": "DOCUMENT_INTELLIGENCE",
    "description": "Directive identifies this capability. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A08",
    "agent_name": "Extraction Validation",
    "category": "DOCUMENT_INTELLIGENCE",
    "description": "Directive identifies this capability. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A09",
    "agent_name": "DOCUMENT INTELLIGENCE 09",
    "category": "DOCUMENT_INTELLIGENCE",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A10",
    "agent_name": "Duplicate / Fraud Check",
    "category": "DOCUMENT_INTELLIGENCE",
    "description": "Directive identifies this capability. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A11",
    "agent_name": "Evidence",
    "category": "DOCUMENT_INTELLIGENCE",
    "description": "Directive identifies this capability. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A12",
    "agent_name": "ACCOUNTING 12",
    "category": "ACCOUNTING",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A13",
    "agent_name": "ACCOUNTING 13",
    "category": "ACCOUNTING",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A14",
    "agent_name": "ACCOUNTING 14",
    "category": "ACCOUNTING",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A15",
    "agent_name": "ACCOUNTING 15",
    "category": "ACCOUNTING",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A16",
    "agent_name": "ACCOUNTING 16",
    "category": "ACCOUNTING",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A17",
    "agent_name": "TAX INTELLIGENCE 17",
    "category": "TAX_INTELLIGENCE",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A18",
    "agent_name": "Federal Tax Analysis",
    "category": "TAX_INTELLIGENCE",
    "description": "Directive identifies this capability. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A19",
    "agent_name": "State Tax Analysis",
    "category": "TAX_INTELLIGENCE",
    "description": "Directive identifies this capability. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A20",
    "agent_name": "TAX INTELLIGENCE 20",
    "category": "TAX_INTELLIGENCE",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A21",
    "agent_name": "TAX INTELLIGENCE 21",
    "category": "TAX_INTELLIGENCE",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A22",
    "agent_name": "TAX INTELLIGENCE 22",
    "category": "TAX_INTELLIGENCE",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A23",
    "agent_name": "TAX INTELLIGENCE 23",
    "category": "TAX_INTELLIGENCE",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A24",
    "agent_name": "TAX INTELLIGENCE 24",
    "category": "TAX_INTELLIGENCE",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A25",
    "agent_name": "TAX INTELLIGENCE 25",
    "category": "TAX_INTELLIGENCE",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A26",
    "agent_name": "TAX INTELLIGENCE 26",
    "category": "TAX_INTELLIGENCE",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A27",
    "agent_name": "TAX INTELLIGENCE 27",
    "category": "TAX_INTELLIGENCE",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A28",
    "agent_name": "Calculation Verification",
    "category": "TAX_INTELLIGENCE",
    "description": "Directive identifies this capability. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A29",
    "agent_name": "TAX INTELLIGENCE 29",
    "category": "TAX_INTELLIGENCE",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A30",
    "agent_name": "Form Mapping",
    "category": "TAX_INTELLIGENCE",
    "description": "Directive identifies this capability. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A31",
    "agent_name": "Diagnostics",
    "category": "TAX_INTELLIGENCE",
    "description": "Directive identifies this capability. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A32",
    "agent_name": "RISK QC 32",
    "category": "RISK_QC",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A33",
    "agent_name": "RISK QC 33",
    "category": "RISK_QC",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A34",
    "agent_name": "Reviewer Support",
    "category": "RISK_QC",
    "description": "Directive identifies this capability. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A35",
    "agent_name": "RISK QC 35",
    "category": "RISK_QC",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A36",
    "agent_name": "SIGN FILE RESOLVE 36",
    "category": "SIGN_FILE_RESOLVE",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A37",
    "agent_name": "SIGN FILE RESOLVE 37",
    "category": "SIGN_FILE_RESOLVE",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A38",
    "agent_name": "SIGN FILE RESOLVE 38",
    "category": "SIGN_FILE_RESOLVE",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A39",
    "agent_name": "SIGN FILE RESOLVE 39",
    "category": "SIGN_FILE_RESOLVE",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A40",
    "agent_name": "SIGN FILE RESOLVE 40",
    "category": "SIGN_FILE_RESOLVE",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A41",
    "agent_name": "SIGN FILE RESOLVE 41",
    "category": "SIGN_FILE_RESOLVE",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A42",
    "agent_name": "SIGN FILE RESOLVE 42",
    "category": "SIGN_FILE_RESOLVE",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A43",
    "agent_name": "PRACTICE OPERATIONS 43",
    "category": "PRACTICE_OPERATIONS",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A44",
    "agent_name": "PRACTICE OPERATIONS 44",
    "category": "PRACTICE_OPERATIONS",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A45",
    "agent_name": "PRACTICE OPERATIONS 45",
    "category": "PRACTICE_OPERATIONS",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A46",
    "agent_name": "PRACTICE OPERATIONS 46",
    "category": "PRACTICE_OPERATIONS",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A47",
    "agent_name": "PRACTICE OPERATIONS 47",
    "category": "PRACTICE_OPERATIONS",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A48",
    "agent_name": "PRACTICE OPERATIONS 48",
    "category": "PRACTICE_OPERATIONS",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A49",
    "agent_name": "PRACTICE OPERATIONS 49",
    "category": "PRACTICE_OPERATIONS",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A50",
    "agent_name": "PRACTICE OPERATIONS 50",
    "category": "PRACTICE_OPERATIONS",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A51",
    "agent_name": "GOVERNANCE SECURITY PLATFORM 51",
    "category": "GOVERNANCE_SECURITY_PLATFORM",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A52",
    "agent_name": "GOVERNANCE SECURITY PLATFORM 52",
    "category": "GOVERNANCE_SECURITY_PLATFORM",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A53",
    "agent_name": "GOVERNANCE SECURITY PLATFORM 53",
    "category": "GOVERNANCE_SECURITY_PLATFORM",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A54",
    "agent_name": "GOVERNANCE SECURITY PLATFORM 54",
    "category": "GOVERNANCE_SECURITY_PLATFORM",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A55",
    "agent_name": "GOVERNANCE SECURITY PLATFORM 55",
    "category": "GOVERNANCE_SECURITY_PLATFORM",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A56",
    "agent_name": "GOVERNANCE SECURITY PLATFORM 56",
    "category": "GOVERNANCE_SECURITY_PLATFORM",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A57",
    "agent_name": "GOVERNANCE SECURITY PLATFORM 57",
    "category": "GOVERNANCE_SECURITY_PLATFORM",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A58",
    "agent_name": "GOVERNANCE SECURITY PLATFORM 58",
    "category": "GOVERNANCE_SECURITY_PLATFORM",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A59",
    "agent_name": "GOVERNANCE SECURITY PLATFORM 59",
    "category": "GOVERNANCE_SECURITY_PLATFORM",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  },
  {
    "agent_id": "A60",
    "agent_name": "GOVERNANCE SECURITY PLATFORM 60",
    "category": "GOVERNANCE_SECURITY_PLATFORM",
    "description": "Exact specialized name requires the missing approved architecture mapping. DRAFT metadata only; no execution authority.",
    "version": "1.0.0",
    "status": "DRAFT",
    "risk_class": "MATERIAL",
    "default_model": null,
    "default_model_version": null,
    "prompt_id": null,
    "prompt_version": null,
    "schema_version": "1",
    "confidence_threshold": 1,
    "human_review_threshold": 1,
    "maximum_execution_time": 30,
    "maximum_retries": 0,
    "token_budget": 0,
    "cost_budget": 0
  }
].map(agent => Object.freeze(agent))) as readonly Readonly<Omit<Agent, 'created_at' | 'updated_at'>>[];

export function findCanonicalAgent(id: string) {
  const agent = CANONICAL_AGENTS.find(candidate => candidate.agent_id === id);
  if (!agent) throw new Error('UNKNOWN_AI_AGENT');
  return agent;
}
